apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}
spec:
  selector:
    app: {{ .Values.auth.name }}
  ports:
    - port: {{ .Values.auth.portNumber }}
      targetPort: {{ .Values.auth.portNumber }}
  type: ClusterIP

